version: '3'
services:
  minio:
    image: bitnami/minio:latest
    container_name: minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=Admin12345678
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
